//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Areas.KVKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KVKK_IdariTedbirGrup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KVKK_IdariTedbirGrup()
        {
            this.KVKK_IdariTedbirGrupDetay = new HashSet<KVKK_IdariTedbirGrupDetay>();
            this.KVKK_TeknikTedbirGrupListe = new HashSet<KVKK_TeknikTedbirGrupListe>();
        }
    
        public int id { get; set; }
        public int idaritedbirgrup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KVKK_IdariTedbirGrupDetay> KVKK_IdariTedbirGrupDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KVKK_TeknikTedbirGrupListe> KVKK_TeknikTedbirGrupListe { get; set; }
    }
}
