//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Areas.KVKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KVKK_Sablon
    {
        public int id { get; set; }
        public int departmanID { get; set; }
        public int kisiselveriID { get; set; }
        public int faaliyetID { get; set; }
        public int verikategoriID { get; set; }
        public bool ozelNitelik { get; set; }
        public int verisahibiID { get; set; }
        public int veriislemeamacID { get; set; }
        public int hukukidayanakID { get; set; }
        public bool yurticiaktarim { get; set; }
        public Nullable<int> veritransferaliciID { get; set; }
        public bool yurtdisiaktarim { get; set; }
        public Nullable<int> idaritedbirgrupID { get; set; }
        public Nullable<int> tekniktedbirgrupID { get; set; }
        public int verisaklamasuresiID { get; set; }
    
        public virtual KVKK_1_VeriSahibi KVKK_1_VeriSahibi { get; set; }
        public virtual KVKK_2_VeriIslemeAmaci KVKK_2_VeriIslemeAmaci { get; set; }
        public virtual KVKK_3_VeriTransferAlici KVKK_3_VeriTransferAlici { get; set; }
        public virtual KVKK_5_VeriSaklamaSuresi KVKK_5_VeriSaklamaSuresi { get; set; }
        public virtual KVKK_Departman KVKK_Departman { get; set; }
        public virtual KVKK_Faaliyet KVKK_Faaliyet { get; set; }
        public virtual KVKK_HukukiDayanak KVKK_HukukiDayanak { get; set; }
        public virtual KVKK_KisiselVeri KVKK_KisiselVeri { get; set; }
        public virtual KVKK_VeriKategori KVKK_VeriKategori { get; set; }
    }
}
