//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Areas.KVKK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KvkkEntities : DbContext
    {
        public KvkkEntities()
            : base("name=KvkkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KVKK_1_VeriSahibi> KVKK_1_VeriSahibi { get; set; }
        public virtual DbSet<KVKK_2_VeriIslemeAmaci> KVKK_2_VeriIslemeAmaci { get; set; }
        public virtual DbSet<KVKK_3_VeriTransferAlici> KVKK_3_VeriTransferAlici { get; set; }
        public virtual DbSet<KVKK_4_VeriGuvenligiAlinanTedbirler> KVKK_4_VeriGuvenligiAlinanTedbirler { get; set; }
        public virtual DbSet<KVKK_5_VeriSaklamaSuresi> KVKK_5_VeriSaklamaSuresi { get; set; }
        public virtual DbSet<KVKK_Departman> KVKK_Departman { get; set; }
        public virtual DbSet<KVKK_Faaliyet> KVKK_Faaliyet { get; set; }
        public virtual DbSet<KVKK_HukukiDayanak> KVKK_HukukiDayanak { get; set; }
        public virtual DbSet<KVKK_IdariTedbir> KVKK_IdariTedbir { get; set; }
        public virtual DbSet<KVKK_IdariTedbirGrup> KVKK_IdariTedbirGrup { get; set; }
        public virtual DbSet<KVKK_IdariTedbirGrupDetay> KVKK_IdariTedbirGrupDetay { get; set; }
        public virtual DbSet<KVKK_KisiselVeri> KVKK_KisiselVeri { get; set; }
        public virtual DbSet<KVKK_TeknikTedbir> KVKK_TeknikTedbir { get; set; }
        public virtual DbSet<KVKK_TeknikTedbirGrup> KVKK_TeknikTedbirGrup { get; set; }
        public virtual DbSet<KVKK_TeknikTedbirGrupListe> KVKK_TeknikTedbirGrupListe { get; set; }
        public virtual DbSet<KVKK_VeriKategori> KVKK_VeriKategori { get; set; }
        public virtual DbSet<KVKK_Sablon> KVKK_Sablon { get; set; }
    }
}
