//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Areas.KVKK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KVKK_TeknikTedbirGrupListe
    {
        public int id { get; set; }
        public int tekniktedbirgrupid { get; set; }
        public int tekniktedbir { get; set; }
    
        public virtual KVKK_IdariTedbirGrup KVKK_IdariTedbirGrup { get; set; }
    }
}
