//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arsiv_Personel
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string sicilno { get; set; }
        public System.DateTime giristarihi { get; set; }
        public System.DateTime cikistarihi { get; set; }
        public Nullable<int> ihaletip { get; set; }
        public Nullable<int> klasorno { get; set; }
    
        public virtual Arsiv_Ihaletip Arsiv_Ihaletip { get; set; }
    }
}
