//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorev_Detay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gorev_Detay()
        {
            this.Gorev_Detay_Not = new HashSet<Gorev_Detay_Not>();
            this.Gorev_Detay1 = new HashSet<Gorev_Detay>();
        }
    
        public int id { get; set; }
        public Nullable<int> parentID { get; set; }
        public string ad { get; set; }
        public bool aktif { get; set; }
        public Nullable<int> sira { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorev_Detay_Not> Gorev_Detay_Not { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorev_Detay> Gorev_Detay1 { get; set; }
        public virtual Gorev_Detay Gorev_Detay2 { get; set; }
    }
}
