//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorev_Detay_Not
    {
        public int id { get; set; }
        public int gorevDetayID { get; set; }
        public string Not { get; set; }
    
        public virtual Gorev_Detay Gorev_Detay { get; set; }
    }
}
