//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ihale
    {
        public int id { get; set; }
        public string dosyano { get; set; }
        public string ihaleadi { get; set; }
        public string isyeritescilno { get; set; }
        public Nullable<decimal> yolucret { get; set; }
        public Nullable<decimal> yemekucret { get; set; }
    }
}
