//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikEntities : DbContext
    {
        public ikEntities()
            : base("name=ikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<birim> birims { get; set; }
        public virtual DbSet<Grup> Grups { get; set; }
        public virtual DbSet<Izin> Izins { get; set; }
        public virtual DbSet<IzinTip> IzinTips { get; set; }
        public virtual DbSet<ihale> ihales { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<PersonelGrup> PersonelGrups { get; set; }
        public virtual DbSet<Takip> Takips { get; set; }
        public virtual DbSet<ImzaTakip> ImzaTakips { get; set; }

        public System.Data.Entity.DbSet<ik.Models.ImzaTakipVM> ImzaTakipVMs { get; set; }
    }
}
