//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImzaTakipDetay
    {
        public int id { get; set; }
        public int takipid { get; set; }
        public int personelID { get; set; }
        public Nullable<System.DateTime> imzaTarih { get; set; }
        public string aciklama { get; set; }
    
        public virtual ImzaTakip ImzaTakip { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
