//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinBakmaYetki
    {
        public int id { get; set; }
        public int ust { get; set; }
        public int alt { get; set; }
    
        public virtual Personel PersonelAlt { get; set; }
        public virtual Personel PersonelUst { get; set; }
    }
}
