//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanunparametre
    {
        public int id { get; set; }
        public int yil { get; set; }
        public decimal brutasgari { get; set; }
        public decimal brutyemek { get; set; }
        public int yemekistisnagun { get; set; }
        public decimal SGKiscipay { get; set; }
        public decimal Issizlikpay { get; set; }
        public decimal Damgavergipay { get; set; }
        public decimal agi { get; set; }
    }
}
