//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurul
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string tc { get; set; }
        public int gorevtip { get; set; }
        public System.DateTime giristarih { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
    
        public virtual KurulGorevTip KurulGorevTip { get; set; }
    }
}
