//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maas_Is_Liste_Detay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maas_Is_Liste_Detay()
        {
            this.Maas_Is_Detay = new HashSet<Maas_Is_Detay>();
        }
    
        public int id { get; set; }
        public int maasIsListeId { get; set; }
        public string ad { get; set; }
        public bool durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maas_Is_Detay> Maas_Is_Detay { get; set; }
        public virtual Maas_Is_Liste Maas_Is_Liste { get; set; }
    }
}
