//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maas_Is_Detay
    {
        public int id { get; set; }
        public int maasIsId { get; set; }
        public int maasIsListeDetayId { get; set; }
        public bool durum { get; set; }
    
        public virtual Maas_Is Maas_Is { get; set; }
        public virtual Maas_Is_Liste_Detay Maas_Is_Liste_Detay { get; set; }
    }
}
