//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzlukGrupTanimDetay
    {
        public int id { get; set; }
        public int ozlukGrupTanımID { get; set; }
        public string ad { get; set; }
    
        public virtual OzlukGrupTanim OzlukGrupTanim { get; set; }
    }
}
