//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozluk_AileFertleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ozluk_AileFertleri()
        {
            this.Ozluk_AileFertleriUrl = new HashSet<Ozluk_AileFertleriUrl>();
        }
    
        public int id { get; set; }
        public int personelID { get; set; }
        public int yakinlikID { get; set; }
        public string adsoyad { get; set; }
        public string dogumYeri { get; set; }
        public System.DateTime dogumTarihi { get; set; }
    
        public virtual Ozluk_Enum_Detay Ozluk_Enum_Detay { get; set; }
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ozluk_AileFertleriUrl> Ozluk_AileFertleriUrl { get; set; }
    }
}
