//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozluk_AileFertleriUrl
    {
        public int id { get; set; }
        public int ailefertID { get; set; }
        public string url { get; set; }
        public string aciklama { get; set; }
    
        public virtual Ozluk_AileFertleri Ozluk_AileFertleri { get; set; }
    }
}
