//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzlukEvrak
    {
        public int id { get; set; }
        public string EvrakAd { get; set; }
        public int adet { get; set; }
        public bool gerekli { get; set; }
    }
}
