//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelDetay
    {
        public int personelid { get; set; }
        public int lokasyon { get; set; }
        public Nullable<int> gorev { get; set; }
        public Nullable<bool> cinsiyeti { get; set; }
        public Nullable<int> tahsili { get; set; }
        public string thumb { get; set; }
        public Nullable<int> okudugubolum { get; set; }
        public Nullable<bool> sirketarac { get; set; }
        public string mailadres { get; set; }
        public Nullable<int> sgkdosya { get; set; }
    
        public virtual Gorev Gorev1 { get; set; }
        public virtual Lokasyon Lokasyon1 { get; set; }
        public virtual Tahsil Tahsil { get; set; }
        public virtual SgkDosya SgkDosya1 { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
