//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelIhaleDonemleri
    {
        public int id { get; set; }
        public int personelid { get; set; }
        public int ihaleid { get; set; }
    
        public virtual PersonelIhale PersonelIhale { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
