//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_SSK_TANIMLARI
    {
        public System.Guid ssk_Guid { get; set; }
        public short ssk_DBCno { get; set; }
        public Nullable<int> ssk_SpecRECno { get; set; }
        public Nullable<bool> ssk_iptal { get; set; }
        public Nullable<short> ssk_fileid { get; set; }
        public Nullable<bool> ssk_hidden { get; set; }
        public Nullable<bool> ssk_kilitli { get; set; }
        public Nullable<bool> ssk_degisti { get; set; }
        public Nullable<int> ssk_checksum { get; set; }
        public Nullable<short> ssk_create_user { get; set; }
        public System.DateTime ssk_create_date { get; set; }
        public Nullable<short> ssk_lastup_user { get; set; }
        public Nullable<System.DateTime> ssk_lastup_date { get; set; }
        public string ssk_special1 { get; set; }
        public string ssk_special2 { get; set; }
        public string ssk_special3 { get; set; }
        public Nullable<int> ssk_Sira_No { get; set; }
        public string ssk_ismi { get; set; }
        public Nullable<byte> ssk_TehlikeDerecesi { get; set; }
        public Nullable<double> ssk_KazaYuzdesi { get; set; }
        public string ssk_subekodu { get; set; }
        public string ssk_BolCalDosNo { get; set; }
        public string ssk_cadde { get; set; }
        public string ssk_mahalle { get; set; }
        public string ssk_sokak { get; set; }
        public string ssk_Adr_Semt { get; set; }
        public string ssk_Apt_No { get; set; }
        public string ssk_Daire_No { get; set; }
        public string ssk_posta_kodu { get; set; }
        public string ssk_ilce { get; set; }
        public string ssk_il { get; set; }
        public string ssk_ulke { get; set; }
        public string ssk_adres_kodu { get; set; }
        public Nullable<byte> ssk_iysinifi { get; set; }
        public string ssk_iykapino { get; set; }
        public string ssk_maasbankakodu { get; set; }
        public string ssk_sskno_Mahiyet { get; set; }
        public string ssk_sskno_Iskolu { get; set; }
        public string ssk_sskno_SubeKodu { get; set; }
        public string ssk_sskno_TehlikeKodu { get; set; }
        public string ssk_sskno_SiraNo { get; set; }
        public string ssk_sskno_IlKodu { get; set; }
        public string ssk_sskno_Ilce { get; set; }
        public string ssk_sskno_Kontrol_No { get; set; }
        public string ssk_AraciKodu { get; set; }
        public string ssk_BolgeMudurlukNo { get; set; }
        public Nullable<System.Guid> ssk_Iskur_uid { get; set; }
        public string ssk_Semt { get; set; }
        public Nullable<double> ssk_N_SSK_Yuzde { get; set; }
        public Nullable<double> ssk_E_SSK_Yuzde { get; set; }
        public Nullable<double> ssk_C_SSK_Yuzde { get; set; }
        public Nullable<double> ssk_Y_SSK_Yuzde { get; set; }
        public Nullable<double> ssk_Ana_Sig { get; set; }
        public Nullable<double> ssk_N_Hast_Sig { get; set; }
        public Nullable<double> ssk_C_Hast_Sig { get; set; }
        public Nullable<double> ssk_Yas_Ol_Sig { get; set; }
        public Nullable<double> ssk_SGDP_Orani { get; set; }
        public string ssk_Calisma_Kodu { get; set; }
        public string ssk_FirmaUnvani { get; set; }
        public string ssk_FirmaUnvani2 { get; set; }
        public string ssk_ebildirge_username { get; set; }
        public string ssk_ebildirge_isyerikod { get; set; }
        public string ssk_ebildirge_password { get; set; }
        public string ssk_ebildirge_isyerisifre { get; set; }
        public Nullable<double> ssk_yasolum_itibarihizmet { get; set; }
        public Nullable<byte> ssk_isverentipi { get; set; }
        public Nullable<double> ssk_genel_saglik_sigortasi { get; set; }
        public Nullable<double> ssk_malulluk_muafiyet { get; set; }
        public Nullable<byte> ssk_5225BelgeTuru { get; set; }
        public Nullable<System.DateTime> ssk_5225BelgeTarihi { get; set; }
        public string ssk_5225BelgeSayisi { get; set; }
        public Nullable<System.DateTime> ssk_GVK80BelgeTarih { get; set; }
        public string ssk_GVK80BelgeNo { get; set; }
        public Nullable<byte> ssk_iskolukodu { get; set; }
        public Nullable<byte> ssk_iskolukodu_new { get; set; }
        public Nullable<bool> ssk_Pasif_fl { get; set; }
        public Nullable<System.DateTime> ssk_AcilisTarihi { get; set; }
        public Nullable<System.DateTime> ssk_KapanisTarihi { get; set; }
        public string ssk_muhtasarisyeri_adi { get; set; }
        public Nullable<byte> ssk_muhtasarisyeri_turu { get; set; }
        public string ssk_muhtasarisyeri_kodu { get; set; }
        public Nullable<byte> ssk_muhtasarisyeri_mulkiyet { get; set; }
        public string ssk_Ticaret_Sicil_No { get; set; }
        public string ssk_Ticaret_Sicil_Mudurlugu { get; set; }
        public string ssk_Nace_Kodu { get; set; }
        public Nullable<int> ssk_FirmaNo { get; set; }
        public Nullable<int> ssk_SubeNo { get; set; }
        public Nullable<double> ssk_gecici_madde_17_gunluk_destek { get; set; }
        public Nullable<bool> ssk_muhsgk_degerlendirilmesin_fl { get; set; }
        public Nullable<int> ssk_KbsTesiskodu { get; set; }
        public Nullable<double> ssk_dulke_iscipayi_ustdilimi { get; set; }
        public Nullable<double> ssk_dulke_iscipayi_ustorani { get; set; }
    }
}
