//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelIhale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonelIhale()
        {
            this.PersonelIhaleDonemleris = new HashSet<PersonelIhaleDonemleri>();
        }
    
        public int id { get; set; }
        public int firmaid { get; set; }
        public System.DateTime baslangic { get; set; }
        public Nullable<System.DateTime> bitis { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelIhaleDonemleri> PersonelIhaleDonemleris { get; set; }
    }
}
