//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staj_Ogrenci_Evrak
    {
        public int id { get; set; }
        public int ogrenciid { get; set; }
        public int evrakid { get; set; }
        public bool alindi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Staj_Evrak Staj_Evrak { get; set; }
        public virtual Staj_Ogrenci Staj_Ogrenci { get; set; }
    }
}
