//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staj_Bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staj_Bolum()
        {
            this.Staj_Ogrenci = new HashSet<Staj_Ogrenci>();
        }
    
        public int id { get; set; }
        public int okulid { get; set; }
        public string ad { get; set; }
    
        public virtual Staj_Okul Staj_Okul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staj_Ogrenci> Staj_Ogrenci { get; set; }
    }
}
