//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staj_Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staj_Ogrenci()
        {
            this.Staj_Ogrenci_Evrak = new HashSet<Staj_Ogrenci_Evrak>();
        }
    
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string telefon { get; set; }
        public Nullable<int> bolumid { get; set; }
        public System.DateTime baslangic { get; set; }
        public System.DateTime bitis { get; set; }
        public string referans { get; set; }
        public int donem { get; set; }
        public bool onayli { get; set; }
        public Nullable<System.DateTime> onaytarih { get; set; }
        public Nullable<System.DateTime> tamamlanmatarih { get; set; }
    
        public virtual Staj_Bolum Staj_Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staj_Ogrenci_Evrak> Staj_Ogrenci_Evrak { get; set; }
    }
}
