//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YizinDetay
    {
        public int id { get; set; }
        public int yizinid { get; set; }
        public string belgesayi { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<System.TimeSpan> baslangic { get; set; }
        public System.TimeSpan bitis { get; set; }
    
        public virtual Yizin Yizin { get; set; }
    }
}
